name: Docker Build

on:
  push:
    branches:
      - master
    paths:
      - '.github/**'
      - 'docker/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build login environment of dockersh
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: yamaoka-kitaguchi-lab/dockersh/dockersh-ubuntu
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          workdir: docker/pacman
          buildargs: context
          snapshot: true
          tags: "latest"
